//Ícones em outline, mesmo estilo dos existentes (24x24, stroke)
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',cart:'<path d="M2 3h3l3 13h11l3-10H6M10 20h.01M18 20h.01"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M3 22v-3a9 9 0 0 1 18 0v3Z"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0l-1 1-1-1a5.5 5.5 0 0 0-7.8 7.8L12 22l8.8-9.6a5.5 5.5 0 0 0 0-7.8Z"/>',box:'<path d="m12 2 10 5v10l-10 5-10-5V7Zm0 10v10M2 7l10 5 10-5M7 4.5l10 5V15"/>',spark:'<path d="m12 2 2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7Z"/>',truck:'<path d="M2 16V6a1 1 0 0 1 1-1h11v11H2Z"/><path d="M14 9h4l4 4v3h-8V9Z"/><circle cx="7" cy="18.5" r="1.8"/><circle cx="17.5" cy="18.5" r="1.8"/>',shield:'<path d="M12 2 4 5v6c0 5 3.4 8.7 8 11 4.6-2.3 8-6 8-11V5Z"/><path d="m9 12 2.2 2.2L15.5 10"/>',card:'<rect x="2.5" y="5.5" width="19" height="13" rx="2"/><path d="M2.5 10h19"/><path d="M6 14.5h4"/>',headset:'<path d="M4 13v-1a8 8 0 0 1 16 0v1"/><rect x="2.5" y="13" width="4" height="6" rx="1.5"/><rect x="17.5" y="13" width="4" height="6" rx="1.5"/><path d="M20 19v.5a3 3 0 0 1-3 3h-3"/>',instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.2" cy="6.8" r="1"/>',youtube:'<rect x="2.5" y="5.5" width="19" height="13" rx="4"/><path d="M10.5 9.3v5.4l5-2.7Z"/>',tiktok:'<path d="M14 3v10.8a3.2 3.2 0 1 1-2.6-3.15"/><path d="M14 3a5.2 5.2 0 0 0 5 4.9V11a8 8 0 0 1-5-1.7"/>',whatsapp:'<path d="M4 20l1.3-3.9A8 8 0 1 1 8.6 19Z"/><path d="M9 9.5c0 3 2.5 5.5 5.5 5.5.6 0 1-.5.8-1l-.4-1.3a.8.8 0 0 0-1-.5l-.9.3a5 5 0 0 1-2.5-2.5l.3-.9a.8.8 0 0 0-.5-1L9 8c-.5-.2-1 .2-1 .8Z"/>',pin:'<path d="M12 21s-7-6.2-7-11a7 7 0 0 1 14 0c0 4.8-7 11-7 11Z"/><circle cx="12" cy="10" r="2.5"/>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[el.dataset.icon]}</svg>`);
const products=[{id:1,name:'Dragão Articulado',price:89.90,category:'Brinquedos',badge:'Mais vendido',color:'#f02270',reviews:128,x:26,y:686,w:144,h:151},{id:2,name:'Luminária Cacto',price:79.90,category:'Decoração',badge:'Novidade',color:'#15803d',reviews:64,x:191,y:686,w:143,h:150},{id:3,name:'Nome Personalizado',price:49.90,category:'Personalizados',badge:'Personalizável',color:'#087fa0',reviews:52,x:356,y:686,w:143,h:150},{id:4,name:'Mario Bros 3D',price:69.90,category:'Geek',badge:'Colecionável',color:'#d78500',reviews:97,x:521,y:686,w:143,h:150},{id:5,name:'Vaso Geométrico',price:39.90,category:'Decoração',badge:'Decoração',color:'#178046',reviews:33,x:687,y:686,w:141,h:150},{id:6,name:'Organizador de Mesa',price:54.90,category:'Utilidades',badge:'Utilidade',color:'#087fa0',reviews:48,x:852,y:686,w:143,h:150}];
const categories=[['Brinquedos','Diversão em 3D','Brinquedos',50,452],['Decoração de Casa','Ambientes únicos','Decoração',215,452],['Personalizados','Seu nome, sua ideia','Personalizados',378,452],['Decorativos','Peças criativas','Decoração',540,452],['Geek & Colecionáveis','Para todas as idades','Geek',705,452],['Utilidades','Soluções do dia a dia','Utilidades',870,452]];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const crop=(x,y,w,h)=>`background-size:${1024/w*100}% ${1536/h*100}%;background-position:${x/(1024-w)*100}% ${y/(1536-h)*100}%`;
const image=p=>`<span class="crop product-image" role="img" aria-label="${p.name}" style="${crop(p.x,p.y,p.w,p.h)}"></span>`;
document.querySelector('.categories').innerHTML=categories.map(([name,sub,key,x,y])=>`<button class="category" data-category="${key}"><span class="crop" style="${crop(x,y,100,95)}" aria-hidden="true"></span><strong>${name}</strong><small>${sub}</small><span class="arrow" aria-hidden="true">→</span></button>`).join('');
let activeCategory='Todos';let searchQuery='';const cart=new Map();const grid=document.querySelector('#product-grid');
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
//Antes o "Presentes" caía num OR solto e virava true pra qualquer categoria por precedência de operador.
//Agora cada categoria tem sua regra explícita: Todos e Presentes mostram o catálogo inteiro (é um catálogo
//pequeno e praticamente tudo serve de presente), Novidades filtra pelo badge, as demais batem a categoria.
function filtered(){
  const query=normalize(searchQuery);
  return products.filter(p=>{
    const matchesQuery=normalize(p.name+' '+p.category).includes(query);
    if(!matchesQuery)return false;
    if(activeCategory==='Todos'||activeCategory==='Presentes')return true;
    if(activeCategory==='Novidades')return p.badge==='Novidade';
    return p.category===activeCategory;
  });
}
function render(){const visible=filtered();grid.innerHTML=visible.map(p=>`<article class="product">${image(p)}<div class="product-body"><span class="badge" style="background:${p.color}">${p.badge}</span><h3>${p.name}</h3><div class="rating" aria-label="Avaliação ilustrativa: 5 de 5, ${p.reviews} avaliações"><span class="stars" aria-hidden="true">★★★★★</span><span>(${p.reviews})</span></div><p class="price">${money(p.price)}</p><button class="button" data-add="${p.id}" aria-label="Adicionar ${p.name} ao carrinho">Comprar</button></div></article>`).join('');document.querySelector('#empty').hidden=visible.length>0;document.querySelector('.filter-state').hidden=activeCategory==='Todos'&&!searchQuery;document.querySelector('#filter-label').textContent=`${activeCategory}${searchQuery?' · “'+searchQuery+'”':''} — ${visible.length} produto${visible.length===1?'':'s'}`;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category===activeCategory);b.setAttribute('aria-pressed',String(b.dataset.category===activeCategory))});}
function selectCategory(category){activeCategory=category;searchQuery='';document.querySelector('#search').value='';render();document.querySelector('#produtos').scrollIntoView({behavior:'smooth'});}
document.addEventListener('click',e=>{const category=e.target.closest('[data-category]');if(category)selectCategory(category.dataset.category);const add=e.target.closest('[data-add]');if(add)addToCart(Number(add.dataset.add));const info=e.target.closest('[data-info]');if(info)showInfo(info.dataset.info);const close=e.target.closest('.close');if(close)close.closest('dialog').close();const qty=e.target.closest('[data-qty]');if(qty){const id=Number(qty.dataset.id);const value=(cart.get(id)||0)+Number(qty.dataset.qty);if(value>0)cart.set(id,value);else cart.delete(id);renderCart()}const remove=e.target.closest('[data-remove]');if(remove){cart.delete(Number(remove.dataset.remove));renderCart()}});
document.querySelector('.search').addEventListener('submit',e=>{e.preventDefault();searchQuery=document.querySelector('#search').value.trim();activeCategory='Todos';render();document.querySelector('#produtos').scrollIntoView({behavior:'smooth'})});
document.querySelector('#search').addEventListener('input',e=>{searchQuery=e.target.value.trim();activeCategory='Todos';render()});
document.querySelector('#show-all').onclick=document.querySelector('#clear-filter').onclick=()=>selectCategory('Todos');
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2800)}
function addToCart(id){const p=products.find(p=>p.id===id);if(!p)throw new Error('Produto não encontrado');cart.set(id,(cart.get(id)||0)+1);renderCart();toast(`${p.name} adicionado ao carrinho`);return{product:p.name,quantity:cart.get(id)}}
function renderCart(){let total=0,count=0;const rows=[...cart].map(([id,q])=>{const p=products.find(p=>p.id===id);total+=p.price*q;count+=q;return`<article class="cart-line">${image(p)}<div><h3>${p.name}</h3><p>${money(p.price*q)}</p><div class="qty"><button data-qty="-1" data-id="${id}" aria-label="Diminuir quantidade de ${p.name}">−</button><span aria-label="Quantidade">${q}</span><button data-qty="1" data-id="${id}" aria-label="Aumentar quantidade de ${p.name}">+</button><button class="remove" data-remove="${id}" aria-label="Remover ${p.name}">Remover</button></div></div></article>`}).join('');document.querySelector('#cart-items').innerHTML=rows||'<p>Seu carrinho está esperando uma boa ideia.</p><p>Explore os produtos e encontre a sua próxima peça favorita.</p>';document.querySelector('#cart-count').textContent=count;document.querySelector('#dialog-count').textContent=count?`(${count})`:'';document.querySelector('#cart-total').textContent=money(total);document.querySelector('#subtotal').textContent=money(total);document.querySelector('#cart-summary').hidden=!count;}
document.querySelector('.cart-open').onclick=()=>document.querySelector('#cart-dialog').showModal();
const information={account:['Minha conta','<p>A área de clientes ainda não está disponível nesta demonstração. Você pode explorar os produtos e montar seu carrinho sem cadastro.</p>'],buy:['Como comprar','<p>Explore as categorias, escolha uma peça e clique em Comprar para adicioná-la ao carrinho. Você pode ajustar as quantidades ou remover produtos a qualquer momento.</p><p>Esta é uma demonstração da loja. Pedidos, pagamentos e entregas ainda não estão habilitados.</p>'],faq:['Perguntas frequentes','<p><strong>Posso personalizar uma peça?</strong><br>A proposta inclui itens personalizados. Cores, medidas e nomes serão combinados no atendimento quando a loja estiver disponível.</p><p><strong>Os produtos estão à venda?</strong><br>Este catálogo reproduz a proposta visual. Imagens, avaliações e preços são ilustrativos; o catálogo final ainda precisa ser confirmado.</p>'],privacy:['Privacidade nesta demonstração','<p>Não solicitamos dados pessoais nem realizamos pagamentos. O carrinho fica somente na memória desta página e é apagado ao recarregar ou fechar.</p><p>A página carrega fontes do Google Fonts. As condições de privacidade da loja deverão ser publicadas antes do início das vendas.</p>'],checkout:['Seu carrinho está pronto','<p>A finalização de pedidos ainda não está habilitada. Esta versão permite experimentar o catálogo e o carrinho, mas não envia pedidos nem realiza cobranças.</p><p>Para começar a vender, será necessário configurar o atendimento, os pagamentos e as opções de entrega.</p>']};
function showInfo(key){const entry=information[key];if(!entry)return;document.querySelector('#info-title').textContent=entry[0];document.querySelector('#info-content').innerHTML=entry[1];document.querySelector('#info-dialog').showModal()}
document.querySelector('.checkout').onclick=()=>showInfo('checkout');
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.querySelector('#year').textContent=new Date().getFullYear();render();renderCart();
//Captura de e-mail do rodapé — ainda sem backend, então só valida e confirma via toast
const newsletterForm=document.querySelector('#newsletter-form');
if(newsletterForm)newsletterForm.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#newsletter-email');if(!input.checkValidity()){input.reportValidity();return}toast('Cadastro recebido! Envio de novidades ainda não está ativo nesta demonstração.');newsletterForm.reset()});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'search_products',description:'Filtra o catálogo demonstrativo e atualiza os produtos visíveis.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},execute(input){if(typeof input?.query!=='string')throw new Error('Informe uma busca em texto');searchQuery=input.query.trim();activeCategory='Todos';document.querySelector('#search').value=searchQuery;render();return{products:filtered().map(({id,name,price})=>({id,name,price}))}}},{name:'add_to_cart',description:'Adiciona um produto ao carrinho de demonstração. Não realiza pedidos ou pagamentos.',inputSchema:{type:'object',properties:{productId:{type:'integer'}},required:['productId'],additionalProperties:false},execute(input){if(!Number.isInteger(input?.productId))throw new Error('Identificador inválido');return addToCart(input.productId)}}]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
