<?php
declare(strict_types=1);
if ($tab === 'orders'):
    $orders=list_orders();
    $paid=array_values(array_filter($orders,fn($o)=>($o['paymentStatus']??'')==='paid'));
    $open=array_values(array_filter($paid,fn($o)=>!in_array($o['fulfillmentStatus']??'', ['delivered','cancelled'],true)));
    $revenue=array_sum(array_map(fn($o)=>(int)($o['totalCents']??0),$paid));
    $filter=(string)($_GET['filter']??'all');
    if ($filter==='open') $orders=$open;
    elseif ($filter==='paid') $orders=$paid;
    elseif ($filter==='pending') $orders=array_values(array_filter($orders,fn($o)=>($o['paymentStatus']??'')!=='paid'));
?>
<div class="page-heading"><div><p class="eyebrow">OPERAÇÃO</p><h1>Pedidos</h1><p>Acompanhe o pagamento e avance o preparo de cada venda.</p></div></div>
<div class="metric-grid"><div class="panel"><small>Pagos</small><strong><?=count($paid)?></strong></div><div class="panel"><small>Para preparar</small><strong><?=count($open)?></strong></div><div class="panel"><small>Total pago</small><strong>R$ <?=e(number_format($revenue/100,2,',','.'))?></strong></div></div>
<p class="filter-links"><a href="?tab=orders">Todos</a><a href="?tab=orders&filter=open">Em andamento</a><a href="?tab=orders&filter=paid">Pagos</a><a href="?tab=orders&filter=pending">Aguardando pagamento</a></p>
<?php foreach($orders as $o): ?><section class="panel order-card">
<div class="panel-heading"><div><h2>Pedido #<?=e(strtoupper(substr($o['id'],0,8)))?></h2><small><?=e($o['createdAt']??'')?> · <?=e($o['customer']['name']??'')?> · <?=e($o['customer']['email']??'')?></small></div><span class="status <?=($o['paymentStatus']??'')==='paid'?'on':'off'?>"><?=($o['paymentStatus']??'')==='paid'?'Pago':'Aguardando pagamento'?></span></div>
<p><strong>Itens:</strong> <?php foreach($o['items']??[] as $line): ?><?=e($line['quantity'])?> × <?=e($line['name'])?>; <?php endforeach; ?></p>
<p><strong>Total:</strong> R$ <?=e(number_format(($o['totalCents']??0)/100,2,',','.'))?> · <strong>Frete:</strong> R$ <?=e(number_format(($o['shippingCents']??0)/100,2,',','.'))?></p>
<?php if(!empty($o['shippingOption']['label'])): ?><p><strong>Modalidade:</strong> <?=e($o['shippingOption']['label'])?><?php if(!empty($o['shippingOption']['deliveryDays'])): ?> · até <?=e($o['shippingOption']['deliveryDays'])?> dias úteis<?php endif; ?></p><?php endif; ?>
<?php if(!empty($o['paymentError'])): ?><p><strong>Falha ao gerar pagamento:</strong> <?=e($o['paymentError'])?></p><?php endif; ?>
<p><strong>Entrega:</strong> <?=e($o['shipping']['street']??'')?>, <?=e($o['shipping']['number']??'')?> <?=e($o['shipping']['complement']??'')?> — <?=e($o['shipping']['city']??'')?> / <?=e($o['shipping']['state']??'')?>, CEP <?=e($o['shipping']['cep']??'')?></p>
<?php if(!empty($o['customer']['phone'])): ?><p><strong>Telefone:</strong> <?=e($o['customer']['phone'])?></p><?php endif; ?>
<?php if(($o['paymentStatus']??'')==='paid'): ?><form method="post" class="form-grid"><?=csrf_input()?><input type="hidden" name="action" value="update_order"><input type="hidden" name="id" value="<?=e($o['id'])?>">
<label>Etapa<select name="fulfillment"><?php foreach(['new'=>'Novo','preparing'=>'Em produção','ready'=>'Pronto para envio','shipped'=>'Enviado','delivered'=>'Entregue','cancelled'=>'Cancelado'] as $key=>$label): ?><option value="<?=e($key)?>" <?=($o['fulfillmentStatus']??'')===$key?'selected':''?>><?=e($label)?></option><?php endforeach; ?></select></label>
<label>Rastreamento<input name="tracking" value="<?=e($o['tracking']??'')?>" maxlength="120"></label><label class="wide">Nota interna<textarea name="internal_note" rows="2"><?=e($o['internalNote']??'')?></textarea></label><div class="wide actions"><button class="primary">Salvar etapa</button></div></form><?php endif; ?>
</section><?php endforeach; ?><?php if(!$orders): ?><div class="panel empty">Nenhum pedido nesta lista.</div><?php endif; ?>
<?php elseif($tab==='users'): require_owner(); $users=staff_users(); $editId=(string)($_GET['edit']??''); $editing=null; foreach($users as $u) if($u['id']===$editId) $editing=$u; ?>
<div class="page-heading"><div><p class="eyebrow">EQUIPE</p><h1>Usuários</h1><p>Administradores gerenciam a loja; operadores acompanham e preparam pedidos.</p></div><a class="primary link-button" href="?tab=users&edit=new">+ Novo usuário</a></div>
<?php if($editId!==''): $u=$editing??['id'=>'','name'=>'','username'=>'','role'=>'operator','active'=>true]; ?><section class="panel"><h2><?=$u['id']?'Editar usuário':'Novo usuário'?></h2><form method="post" class="form-grid"><?=csrf_input()?><input type="hidden" name="action" value="save_user"><input type="hidden" name="id" value="<?=e($u['id'])?>"><label>Nome<input name="name" required value="<?=e($u['name'])?>"></label><label>Usuário<input name="username" required pattern="[a-z0-9._-]{3,50}" value="<?=e($u['username'])?>"></label><label>Função<select name="role"><option value="operator" <?=$u['role']==='operator'?'selected':''?>>Operador de pedidos</option><option value="admin" <?=$u['role']==='admin'?'selected':''?>>Administrador</option></select></label><label>Senha <?=!$u['id']?'(obrigatória)':'(deixe vazia para manter)'?><input name="password" type="password" minlength="12" <?=!$u['id']?'required':''?> autocomplete="new-password"></label><label class="wide check"><input type="checkbox" name="active" <?=$u['active']?'checked':''?>> Acesso ativo</label><div class="wide actions"><button class="primary">Salvar usuário</button><a href="?tab=users">Cancelar</a></div></form></section><?php endif; ?>
<section class="panel"><h2>Equipe</h2><div class="list"><?php foreach($users as $u): ?><article class="item"><div class="item-main"><strong><?=e($u['name'])?></strong><small><?=e($u['username'])?> · <?=$u['role']==='admin'?'Administrador':'Operador'?></small></div><span class="status <?=$u['active']?'on':'off'?>"><?=$u['active']?'Ativo':'Inativo'?></span><a href="?tab=users&edit=<?=e($u['id'])?>">Editar</a></article><?php endforeach; ?></div></section>
<?php elseif($tab==='payment'): require_owner(); $p=payment_settings(); ?>
<div class="page-heading"><div><p class="eyebrow">CHECKOUT</p><h1>Pagamentos</h1><p>Configure o Checkout Integrado da InfinitePay para receber Pix e cartão.</p></div></div>
<section class="panel"><h2>Pagamento e frete</h2><p>Os CEPs cadastrados abaixo recebem frete grátis. Para os demais, a loja consulta as transportadoras pelo Melhor Envio antes de criar o pagamento.</p><form method="post" class="form-grid"><?=csrf_input()?><input type="hidden" name="action" value="save_payment"><label>InfiniteTag<input name="handle" value="<?=e($p['handle']??'')?>" placeholder="sua_tag" autocomplete="off"></label><label>CEP de origem da postagem<input name="origin_cep" inputmode="numeric" value="<?=e($p['originCep']??'')?>" placeholder="65000-000"></label><label>E-mail da conta Melhor Envio<input name="shipping_email" type="email" value="<?=e($p['shippingEmail']??'')?>"></label><label>Token Melhor Envio <small><?=!empty($p['melhorEnvioToken'])?'Token salvo; deixe vazio para manter':'Gerado na sua conta Melhor Envio'?></small><input name="melhor_envio_token" type="password" autocomplete="new-password" placeholder="<?=!empty($p['melhorEnvioToken'])?'Token já configurado':'Cole o token aqui'?>"></label><label class="wide">Faixas de CEP com frete grátis <small>Uma por linha, no formato 65000-001 a 65099-999</small><textarea name="free_shipping_ranges" rows="3"><?=e(format_shipping_ranges($p['freeShippingRanges']??[]))?></textarea></label><label class="wide check"><input type="checkbox" name="enabled" <?=!empty($p['enabled'])?'checked':''?>> Ativar pagamento no checkout</label><div class="wide actions"><button class="primary">Salvar configuração</button></div></form></section>
<section class="panel"><h2>Retorno e confirmação</h2><p>Ao pagar, o cliente retorna ao site. O servidor confirma o valor e a transação pela API da InfinitePay antes de marcar o pedido como pago. O webhook também confirma pagamentos quando o cliente não volta à loja.</p><p><strong>Webhook:</strong> <code><?=e(STORE_URL)?>/api/webhook.php</code></p></section>
<?php endif; ?>
